FROM php:8.3-fpm-alpine

# Install system dependencies and PHP extensions

RUN apk add --no-cache nginx wget git openssh-client postgresql-dev \
    && docker-php-ext-install pdo pdo_pgsql


# Install Composer
RUN curl -sS https://getcomposer.org | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www
COPY . .

# Install production dependencies
RUN composer install --no-dev --optimize-autoloader

# Copy Nginx config
COPY nginx.conf /etc/nginx/http.d/default.conf

# Set permissions for storage and bootstrap cache
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 80

CMD nginx && php-fpm
